### ISSUE TITLE
RuntimeError: Given input size: (1504x1x1). Calculated output size: (1504x0x0). Output size is too small

### ISSUE THREAD

**Issue by aaron851113** [AnnaAraslanova/FBNet#11]
When I run :
$ python architecture_main_file.py --architecture_name fbnet_cpu_sample1
I got a error message that said RuntimeError Output size is too small
:red_circle: 
RuntimeError: Given input size: (1504x1x1). Calculated output size: (1504x0x0). Output size is too small
:red_circle: 

Does anyone have this problem too ?

**Comment by AnnaAraslanova** [comment]
It's because of a new version of PyTorch, if you use the dockerfile from the readme, it was updated and the code doesn't work with the new version of pytorch.

**Comment by aaron851113** [comment]
thanks for your help!
By upgrading my torch==1.0.1 , I run the code successfully .

**Comment by gongliyu** [comment]
Can anybody tell me how to solve this problem? My PyTorch version is 1.4.0 but got the same problem. For some reason, I have to make it work in this version of PyTorch? Why different version of PyTorch will cause this problem?

**Comment by weihui98** [comment]
> It's because of a new version of PyTorch, if you use the dockerfile from the readme, it was updated and the code doesn't work with the new version of pytorch.
Hello! I use the version of pytorch: 0.4.1 that is the same with you. But I also have this error.....
Could you tell me some more details?
Thanks!

**Comment by aaron851113** [comment]
Hi @weihui98 , I think that you can try to use Pytorch : 1.0.1 , I run the codes successfully on this pytorch version.

**Comment by weihui98** [comment]
> Hi @weihui98 , I think that you can try to use Pytorch : 1.0.1 , I run the codes successfully on this pytorch version.

Thanks! I just run in this verision pytorch: 1.0.1 successfully.
