### ISSUE TITLE
Question regarding MixedOperations.forward()

### ISSUE THREAD

**Issue by Catosine** [AnnaAraslanova/FBNet#6]
Hello @AnnaAraslanova 

Thanks again for your implementation!
I've got a question about your MixedOperation.forward(). I think it is different from what was described in the paper.
Would you mind double check that?

Thanks!

**Comment by latifisalar** [comment]
Which part do you think is not matching the description in the paper?

**Comment by Catosine** [comment]
Hi, @latifisalar !

Here is the thing: in the paper, the output of each layer seems to be only one of the candidates, controlled by a random variable in the range of {0, 1} (See equation 5 in the paper). 

However, in the MixedOperations.foward(), the output of each layer is the weighted sum of all candidates. 

I've also noticed that @AnnaAraslanova uses the random sampling w.r.t. theta to select the final architecture in supernet_main_file.sample_architecture_from_the_supernet(). I cannot agree with it, for this sampling cannot guarantee a good model. (For example, if someone is super unlucky, he/she would probably get a structure full of skip-connects, due to the randomness.)

Thanks! Let me know if you have some different understanding with this part.

**Comment by AnnaAraslanova** [comment]
@Catosine, @latifisalar
Hi
1) Equation (5) corresponds to the inference step (architecture training), and m_i we relaxed with the Gumbel variables as in the forward step
2) The optimization procedure cannot give any theoretical guarantees to the optimal results. This is only a heuristic approach now
