### ISSUE TITLE
RuntimeError:Output size is too small 

### ISSUE THREAD

**Issue by ldd91** [AnnaAraslanova/FBNet#9]
@AnnaAraslanova  Thanks for your excellent work,I run python supernet_main_file.py --train_or_sample train to search in cifar10,however i account an error:RUntime: Given input size (1504x1x1),Calculated output size:(1504x0x0).Output size is too small.My pytorch version 1.0.1 and my torchvision is o.4.0

**Comment by BshoterJ** [comment]
Hi，I met the same question，and how did you fix it？
Thanks!
